// Mock Users Data
export const mockUsers = [
  {
    id: 1,
    role: "intern",
    username: "john.intern",
    name: "John Doe",
    email: "john.doe@company.com",
    phone: "+1 (555) 123-4567",
    department: "Engineering",
    squad_id: "squad_1",
    line_manager_id: 4,
    interests: ["JavaScript", "Machine Learning", "UI Design"],
    bio: "Passionate software engineering intern with a love for full-stack development and AI.",
    profile_picture: null,
    start_date: "2024-06-01",
    end_date: "2024-08-30",
    onboarding_completed: false,
    first_login: true,
  },
  {
    id: 2,
    role: "intern",
    username: "sarah.intern",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    phone: "+1 (555) 234-5678",
    department: "Marketing",
    squad_id: "squad_1",
    line_manager_id: 5,
    interests: ["Digital Marketing", "Content Creation", "Analytics"],
    bio: "Creative marketing intern focused on digital strategies and brand development.",
    profile_picture: null,
    start_date: "2024-06-01",
    end_date: "2024-08-30",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 3,
    role: "intern",
    username: "mike.intern",
    name: "Mike Chen",
    email: "mike.chen@company.com",
    phone: "+1 (555) 345-6789",
    department: "Design",
    squad_id: "squad_1",
    line_manager_id: 6,
    interests: ["UI/UX Design", "Prototyping", "User Research"],
    bio: "Design intern passionate about creating intuitive user experiences.",
    profile_picture: null,
    start_date: "2024-06-01",
    end_date: "2024-08-30",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 4,
    role: "line_manager",
    username: "sarah.manager",
    name: "Sarah Wilson",
    email: "sarah.wilson@company.com",
    department: "Engineering",
    assigned_interns: [1],
  },
  {
    id: 5,
    role: "line_manager",
    username: "david.manager",
    name: "David Brown",
    email: "david.brown@company.com",
    department: "Marketing",
    assigned_interns: [2],
  },
  {
    id: 6,
    role: "line_manager",
    username: "lisa.manager",
    name: "Lisa Garcia",
    email: "lisa.garcia@company.com",
    department: "Design",
    assigned_interns: [3],
  },
  {
    id: 7,
    role: "hr_admin",
    username: "admin.hr",
    name: "Admin User",
    email: "admin@company.com",
    department: "Human Resources",
  },
]

// Mock Squads Data
export const mockSquads = [
  {
    id: "squad_1",
    name: "Summer 2024 Tech Squad",
    members: [1, 2, 3],
    description: "Cross-functional squad for summer 2024 interns",
    created_date: "2024-05-15",
  },
]

// Mock Onboarding Tasks
export const mockOnboardingTasks = [
  {
    id: 1,
    category: "Bio",
    title: "Complete Profile Information",
    description: "Fill out your personal details and interests",
    completed: true,
    required: true,
    order: 1,
  },
  {
    id: 2,
    category: "Bio",
    title: "Upload Profile Picture",
    description: "Add a professional profile photo",
    completed: false,
    required: false,
    order: 2,
  },
  {
    id: 3,
    category: "IT Tools",
    title: "Laptop Setup",
    description: "Configure your development environment",
    completed: true,
    required: true,
    order: 3,
    eta: "2024-06-05",
  },
  {
    id: 4,
    category: "IT Tools",
    title: "Access Card",
    description: "Collect your building access card",
    completed: false,
    required: true,
    order: 4,
    eta: "2024-06-03",
  },
  {
    id: 5,
    category: "IT Tools",
    title: "Software Licenses",
    description: "Activate required software licenses",
    completed: true,
    required: true,
    order: 5,
  },
  {
    id: 6,
    category: "HR Documents",
    title: "Contract Signing",
    description: "Sign your internship agreement",
    completed: false,
    required: true,
    order: 6,
    eta: "2024-06-01",
  },
  {
    id: 7,
    category: "HR Documents",
    title: "Emergency Contacts",
    description: "Provide emergency contact information",
    completed: false,
    required: true,
    order: 7,
  },
  {
    id: 8,
    category: "HR Documents",
    title: "Bank Details",
    description: "Submit banking information for payroll",
    completed: false,
    required: true,
    order: 8,
  },
]

// Available interests for selection
export const availableInterests = [
  "JavaScript",
  "Python",
  "React",
  "Node.js",
  "Machine Learning",
  "AI",
  "UI Design",
  "UX Research",
  "Prototyping",
  "Digital Marketing",
  "Content Creation",
  "Analytics",
  "Data Science",
  "Cloud Computing",
  "Mobile Development",
  "DevOps",
  "Cybersecurity",
  "Blockchain",
  "Product Management",
  "Project Management",
  "Agile",
  "Scrum",
]

// Mock Posts Data for Social Feed
export const mockPosts = [
  {
    id: 1,
    author_id: 1,
    author_name: "John Doe",
    content:
      "Just finished setting up my development environment! Excited to start working on some real projects. Any tips for a new engineering intern?",
    timestamp: "2024-06-02T10:30:00Z",
    scope: "all", // "all" or "squad"
    squad_id: "squad_1",
    likes: 5,
    comments: 2,
  },
  {
    id: 2,
    author_id: 2,
    author_name: "Sarah Johnson",
    content: "Working on a new marketing campaign for our summer project. The creative process is so inspiring! 🎨",
    timestamp: "2024-06-02T14:15:00Z",
    scope: "squad",
    squad_id: "squad_1",
    likes: 8,
    comments: 3,
  },
  {
    id: 3,
    author_id: 3,
    author_name: "Mike Chen",
    content:
      "Prototyped my first user interface today. The feedback from my mentor was incredibly helpful. Design thinking is fascinating!",
    timestamp: "2024-06-02T16:45:00Z",
    scope: "all",
    squad_id: "squad_1",
    likes: 12,
    comments: 4,
  },
  {
    id: 4,
    author_id: 1,
    author_name: "John Doe",
    content: "Squad lunch was amazing! Great to connect with everyone outside of work. Team bonding is so important.",
    timestamp: "2024-06-01T13:20:00Z",
    scope: "squad",
    squad_id: "squad_1",
    likes: 6,
    comments: 1,
  },
  {
    id: 5,
    author_id: 2,
    author_name: "Sarah Johnson",
    content:
      "Attended my first company all-hands meeting today. The vision and culture here are truly inspiring. Proud to be part of this team!",
    timestamp: "2024-06-01T17:30:00Z",
    scope: "all",
    squad_id: "squad_1",
    likes: 15,
    comments: 6,
  },
]

// Mock Ratings Data
export const mockRatings = [
  {
    id: 1,
    rater_id: 1,
    rater_name: "John Doe",
    ratee_id: 2,
    ratee_name: "Sarah Johnson",
    rating: 5,
    feedback: "Sarah is incredibly creative and always brings fresh ideas to our squad discussions. Great team player!",
    category: "peer", // "peer" or "manager"
    timestamp: "2024-06-01T14:30:00Z",
  },
  {
    id: 2,
    rater_id: 1,
    rater_name: "John Doe",
    ratee_id: 4,
    ratee_name: "Sarah Wilson",
    rating: 4,
    feedback: "Sarah provides excellent guidance and is always available when I need help. Very supportive manager.",
    category: "manager",
    timestamp: "2024-06-01T16:45:00Z",
  },
  {
    id: 3,
    rater_id: 2,
    rater_name: "Sarah Johnson",
    ratee_id: 1,
    ratee_name: "John Doe",
    rating: 4,
    feedback: "John is very dedicated and asks great questions. His technical skills are impressive for an intern.",
    category: "peer",
    timestamp: "2024-06-02T09:15:00Z",
  },
  {
    id: 4,
    rater_id: 3,
    rater_name: "Mike Chen",
    ratee_id: 1,
    ratee_name: "John Doe",
    rating: 5,
    feedback: "John has been super helpful with technical questions and is always willing to collaborate.",
    category: "peer",
    timestamp: "2024-06-02T11:20:00Z",
  },
]

// Mock Knowledge Base Files
export const mockKnowledgeFiles = [
  {
    id: 1,
    name: "Employee Handbook 2024.pdf",
    category: "HR Documents",
    size: "2.4 MB",
    type: "pdf",
    uploaded_by: "HR Admin",
    upload_date: "2024-05-15T10:00:00Z",
    downloads: 45,
  },
  {
    id: 2,
    name: "IT Setup Guide.docx",
    category: "IT Tools",
    size: "1.2 MB",
    type: "docx",
    uploaded_by: "IT Team",
    upload_date: "2024-05-20T14:30:00Z",
    downloads: 32,
  },
  {
    id: 3,
    name: "Company Org Chart.png",
    category: "General",
    size: "856 KB",
    type: "png",
    uploaded_by: "HR Admin",
    upload_date: "2024-05-25T09:15:00Z",
    downloads: 28,
  },
  {
    id: 4,
    name: "Internship Program Overview.pptx",
    category: "Onboarding",
    size: "3.1 MB",
    type: "pptx",
    uploaded_by: "HR Admin",
    upload_date: "2024-06-01T11:45:00Z",
    downloads: 67,
  },
  {
    id: 5,
    name: "Code of Conduct.pdf",
    category: "HR Documents",
    size: "1.8 MB",
    type: "pdf",
    uploaded_by: "Legal Team",
    upload_date: "2024-05-10T16:20:00Z",
    downloads: 41,
  },
]

// Mock Mentors Data
export const mockMentors = [
  {
    id: 101,
    name: "Alex Thompson",
    department: "Engineering",
    role: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js", "Machine Learning"],
    current_mentees: 2,
    max_mentees: 3,
    rating: 4.8,
    bio: "Experienced full-stack developer with 8+ years in the industry. Passionate about mentoring junior developers.",
  },
  {
    id: 102,
    name: "Maria Rodriguez",
    department: "Design",
    role: "Senior UX Designer",
    expertise: ["UI/UX Design", "Prototyping", "User Research", "Design Systems"],
    current_mentees: 1,
    max_mentees: 2,
    rating: 4.9,
    bio: "Award-winning designer with expertise in user-centered design and design thinking methodologies.",
  },
  {
    id: 103,
    name: "David Kim",
    department: "Marketing",
    role: "Marketing Director",
    expertise: ["Digital Marketing", "Content Creation", "Analytics", "Brand Strategy"],
    current_mentees: 3,
    max_mentees: 4,
    rating: 4.7,
    bio: "Strategic marketing leader with proven track record in building successful digital campaigns.",
  },
  {
    id: 104,
    name: "Jennifer Chen",
    department: "Engineering",
    role: "Data Scientist",
    expertise: ["Python", "Machine Learning", "Data Science", "AI"],
    current_mentees: 1,
    max_mentees: 2,
    rating: 4.6,
    bio: "PhD in Computer Science with specialization in machine learning and artificial intelligence.",
  },
]
