// Mock Users Data
export const mockUsers = [
  {
    id: 1,
    role: "intern",
    username: "adebayo.intern",
    name: "Adebayo Ogundimu",
    email: "adebayo.ogundimu@company.com",
    phone: "+234 803 123 4567",
    department: "Engineering and Design",
    squad_id: "siwes_2025_jan",
    mentorship_group_id: "engineering_tech",
    line_manager_id: 7,
    interests: ["Network Planning", "CAD Design", "5G Technology", "Technical Design", "Infrastructure Planning"],
    program: "SIWES",
    bio: "Engineering student passionate about telecommunications infrastructure and 5G network design.",
    profile_picture: null,
    start_date: "2025-01-15",
    end_date: "2025-12-31",
    onboarding_completed: false,
    first_login: true,
  },
  {
    id: 2,
    role: "intern",
    username: "chinelo.intern",
    name: "Chinelo Okechukwu",
    email: "chinelo.okechukwu@company.com",
    phone: "+234 805 234 5678",
    department: "Commercial Department",
    squad_id: "siwes_2025_jan",
    mentorship_group_id: "business_strategy",
    line_manager_id: 8,
    interests: [
      "Business Development",
      "Strategic Planning",
      "Client Relations",
      "Market Research",
      "Commercial Acumen",
    ],
    program: "SIWES",
    bio: "Business student focused on telecommunications market development and strategic partnerships.",
    profile_picture: null,
    start_date: "2025-01-15",
    end_date: "2025-12-31",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 3,
    role: "intern",
    username: "ibrahim.intern",
    name: "Ibrahim Musa",
    email: "ibrahim.musa@company.com",
    phone: "+234 807 345 6789",
    department: "IT Department",
    squad_id: "siwes_2025_jan",
    mentorship_group_id: "software_tech",
    line_manager_id: 13,
    interests: ["Cybersecurity", "Network Management", "Data Analysis", "System Design", "Cloud Computing"],
    program: "SIWES",
    bio: "Computer Science student specializing in network security and system administration.",
    profile_picture: null,
    start_date: "2025-01-15",
    end_date: "2025-12-31",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 4,
    role: "intern",
    username: "funmi.intern",
    name: "Funmilayo Adeyemi",
    email: "funmilayo.adeyemi@company.com",
    phone: "+234 809 456 7890",
    department: "Finance Department",
    squad_id: "nysc_2025_batch_a",
    mentorship_group_id: "finance_analytics",
    line_manager_id: 12,
    interests: [
      "Financial Analysis",
      "Data Analytics",
      "Corporate Finance",
      "Investment Evaluation",
      "Risk Assessment",
    ],
    program: "NYSC",
    bio: "Finance graduate contributing analytical skills to telecommunications infrastructure investment analysis.",
    profile_picture: null,
    start_date: "2025-03-01",
    end_date: "2026-03-31",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 5,
    role: "intern",
    username: "kemi.intern",
    name: "Kemi Bamgbose",
    email: "kemi.bamgbose@company.com",
    phone: "+234 811 567 8901",
    department: "Corporate Communications",
    squad_id: "siwes_2025_jul",
    mentorship_group_id: "communications_marketing",
    line_manager_id: 11,
    interests: [
      "Content Creation",
      "Digital Marketing",
      "Brand Management",
      "Communication Strategy",
      "Creative Thinking",
    ],
    program: "SIWES",
    bio: "Communications student focused on building brand awareness for telecommunications infrastructure services.",
    profile_picture: null,
    start_date: "2025-07-01",
    end_date: "2026-06-30",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 6,
    role: "intern",
    username: "chidiebere.intern",
    name: "Chidiebere Okafor",
    email: "chidiebere.okafor@company.com",
    phone: "+234 813 678 9012",
    department: "Project Delivery",
    squad_id: "isap_2025_q1",
    mentorship_group_id: "project_management",
    line_manager_id: 9,
    interests: [
      "Project Management",
      "Infrastructure Development",
      "Process Improvement",
      "Leadership",
      "Resource Management",
    ],
    program: "ISAP",
    bio: "Graduate trainee specializing in telecommunications infrastructure project delivery and stakeholder coordination.",
    profile_picture: null,
    start_date: "2025-01-01",
    end_date: "2026-06-30",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 8,
    role: "intern",
    username: "tolu.intern",
    name: "Tolu Adeyinka",
    email: "tolu.adeyinka@company.com",
    phone: "+234 815 789 0123",
    department: "Network & Systems Performance",
    squad_id: "tsap_2025_q2",
    mentorship_group_id: "engineering_tech",
    line_manager_id: 8,
    interests: [
      "Network Engineering",
      "System Performance",
      "Technical Problem Solving",
      "Infrastructure Planning",
      "Innovation",
    ],
    program: "TSAP",
    bio: "Technical graduate focused on optimizing telecommunications network performance and reliability.",
    profile_picture: null,
    start_date: "2025-04-01",
    end_date: "2025-12-31",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 9,
    role: "intern",
    username: "ada.intern",
    name: "Ada Okonkwo",
    email: "ada.okonkwo@company.com",
    phone: "+234 817 890 1234",
    department: "Sustainability",
    squad_id: "nysc_2025_batch_a",
    mentorship_group_id: "engineering_tech",
    line_manager_id: 10,
    interests: [
      "Environmental Science",
      "Sustainability",
      "ESG Frameworks",
      "Renewable Energy",
      "Environmental Impact",
    ],
    program: "NYSC",
    bio: "Environmental Science graduate driving sustainable practices in telecommunications infrastructure development.",
    profile_picture: null,
    start_date: "2025-03-01",
    end_date: "2026-03-31",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 10,
    role: "intern",
    username: "bola.intern",
    name: "Bola Adesanya",
    email: "bola.adesanya@company.com",
    phone: "+234 819 901 2345",
    department: "Technical Quality Management & Organisational Performance",
    squad_id: "nysc_2025_batch_a",
    mentorship_group_id: "project_management",
    line_manager_id: 7,
    interests: [
      "Quality Management",
      "Process Optimization",
      "Data Analysis",
      "Performance Metrics",
      "Continuous Improvement",
    ],
    program: "NYSC",
    bio: "Quality Management graduate focused on optimizing telecommunications infrastructure performance standards.",
    profile_picture: null,
    start_date: "2025-03-01",
    end_date: "2026-03-31",
    onboarding_completed: true,
    first_login: false,
  },
  {
    id: 7,
    role: "line_manager",
    username: "sarah.manager",
    name: "Sarah Okonkwo",
    email: "sarah.okonkwo@company.com",
    department: "Engineering and Design",
    role_title: "Senior Engineering Manager",
    assigned_interns: [1, 10],
  },
  {
    id: 8,
    role: "line_manager",
    username: "david.manager",
    name: "David Adeleke",
    email: "david.adeleke@company.com",
    department: "Commercial Department",
    role_title: "Commercial Operations Manager",
    assigned_interns: [2, 8],
  },
  {
    id: 9,
    role: "line_manager",
    username: "segun.manager",
    name: "Segun Oladele",
    email: "segun.oladele@company.com",
    department: "Project Delivery",
    role_title: "Project Delivery Manager",
    assigned_interns: [6],
  },
  {
    id: 10,
    role: "line_manager",
    username: "chioma.manager",
    name: "Chioma Eze",
    email: "chioma.eze@company.com",
    department: "Sustainability",
    role_title: "Sustainability Director",
    assigned_interns: [9],
  },
  {
    id: 11,
    role: "line_manager",
    username: "kemi.manager",
    name: "Kemi Bamgbose",
    email: "kemi.bamgbose@company.com",
    department: "Corporate Communications",
    role_title: "Communications Manager",
    assigned_interns: [5],
  },
  {
    id: 12,
    role: "line_manager",
    username: "kola.manager",
    name: "Kola Adesina",
    email: "kola.adesina@company.com",
    department: "Finance Department",
    role_title: "Finance Manager",
    assigned_interns: [4],
  },
  {
    id: 13,
    role: "line_manager",
    username: "ibrahim.manager",
    name: "Ibrahim Musa",
    email: "ibrahim.musa.manager@company.com",
    department: "IT Department",
    role_title: "IT Manager",
    assigned_interns: [3],
  },
  {
    id: 14,
    role: "hr_admin",
    username: "admin.hr",
    name: "Folake Adesanya",
    email: "folake.adesanya@company.com",
    department: "HR (Human Resources)",
    role_title: "HR Director",
  },
]

// Mock Squads Data
export const mockSquads = [
  {
    id: "siwes_2025_jan",
    name: "SIWES 2025 - January Intake",
    program: "SIWES",
    year: 2025,
    intake: "January",
    endDate: new Date("2025-12-31"),
    members: [1, 2, 3],
    description: "University students gaining practical industry experience - January 2025 intake",
  },
  {
    id: "siwes_2025_jul",
    name: "SIWES 2025 - July Intake",
    program: "SIWES",
    year: 2025,
    intake: "July",
    endDate: new Date("2026-06-30"),
    members: [5],
    description: "University students gaining practical industry experience - July 2025 intake",
  },
  {
    id: "isap_2025_q1",
    name: "ISAP 2025 - Q1 Cohort",
    program: "ISAP",
    year: 2025,
    intake: "Q1",
    endDate: new Date("2026-06-30"),
    members: [6],
    description: "Graduate trainee program for intensive skill development - Q1 2025 cohort",
  },
  {
    id: "tsap_2025_q2",
    name: "TSAP 2025 - Q2 Cohort",
    program: "TSAP",
    year: 2025,
    intake: "Q2",
    endDate: new Date("2025-12-31"),
    members: [8],
    description: "Graduate trainee program focused on technical competencies - Q2 2025 cohort",
  },
  {
    id: "nysc_2025_batch_a",
    name: "NYSC 2025 - Batch A",
    program: "NYSC",
    year: 2025,
    intake: "Batch A",
    endDate: new Date("2026-03-31"),
    members: [4, 9, 10],
    description: "National service participants contributing to organizational goals - Batch A 2025",
  },
]

// Mock Onboarding Tasks
export const mockOnboardingTasks = [
  {
    id: 1,
    category: "Bio",
    title: "Complete Profile Information",
    description: "Fill out your personal details and interests",
    completed: true,
    required: true,
    order: 1,
  },
  {
    id: 2,
    category: "Bio",
    title: "Upload Profile Picture",
    description: "Add a professional profile photo",
    completed: false,
    required: false,
    order: 2,
  },
  {
    id: 3,
    category: "IT Tools",
    title: "Laptop Setup",
    description: "Configure your development environment",
    completed: true,
    required: true,
    order: 3,
    eta: "2024-06-05",
  },
  {
    id: 4,
    category: "IT Tools",
    title: "Access Card",
    description: "Collect your building access card",
    completed: false,
    required: true,
    order: 4,
    eta: "2024-06-03",
  },
  {
    id: 5,
    category: "IT Tools",
    title: "Software Licenses",
    description: "Activate required software licenses",
    completed: true,
    required: true,
    order: 5,
  },
  {
    id: 6,
    category: "HR Documents",
    title: "Contract Signing",
    description: "Sign your internship agreement",
    completed: false,
    required: true,
    order: 6,
    eta: "2024-06-01",
  },
  {
    id: 7,
    category: "HR Documents",
    title: "Emergency Contacts",
    description: "Provide emergency contact information",
    completed: false,
    required: true,
    order: 7,
  },
  {
    id: 8,
    category: "HR Documents",
    title: "Bank Details",
    description: "Submit banking information for payroll",
    completed: false,
    required: true,
    order: 8,
  },
]

// Comprehensive mentorship groups data
export const mockMentorshipGroups = [
  {
    id: "software_tech",
    name: "Software & Technology Career Track",
    members: [3],
    sharedInterests: ["Cybersecurity", "Network Management", "Data Analysis", "System Design", "Cloud Computing"],
    createdDate: new Date("2025-01-15"),
    description: "For interns interested in software development, system administration, and technical careers",
    careerPaths: ["Software Engineer", "System Administrator", "Technical Architect", "DevOps Engineer"],
  },
  {
    id: "engineering_tech",
    name: "Engineering & Technical Career Track",
    members: [1, 8, 9],
    sharedInterests: [
      "Technical Design",
      "Engineering Principles",
      "Infrastructure Planning",
      "Technical Problem Solving",
      "Innovation",
    ],
    createdDate: new Date("2025-01-15"),
    description: "For interns interested in engineering, design, and technical infrastructure careers",
    careerPaths: ["Network Engineer", "Infrastructure Architect", "Technical Consultant", "Engineering Manager"],
  },
  {
    id: "business_strategy",
    name: "Business & Strategy Career Track",
    members: [2],
    sharedInterests: [
      "Business Development",
      "Strategic Planning",
      "Client Relations",
      "Market Research",
      "Commercial Acumen",
    ],
    createdDate: new Date("2025-01-15"),
    description: "For interns interested in business leadership, strategy, and commercial careers",
    careerPaths: ["Business Analyst", "Strategy Consultant", "Product Manager", "Business Development"],
  },
  {
    id: "finance_analytics",
    name: "Finance & Analytics Career Track",
    members: [4],
    sharedInterests: [
      "Financial Analysis",
      "Data Analytics",
      "Corporate Finance",
      "Investment Evaluation",
      "Risk Assessment",
    ],
    createdDate: new Date("2025-03-01"),
    description: "For interns interested in finance, data analysis, and quantitative careers",
    careerPaths: ["Financial Analyst", "Data Scientist", "Investment Analyst", "Risk Manager"],
  },
  {
    id: "project_management",
    name: "Project & Operations Management Track",
    members: [6, 10],
    sharedInterests: [
      "Project Management",
      "Process Optimization",
      "Leadership",
      "Resource Management",
      "Organizational Skills",
    ],
    createdDate: new Date("2025-01-01"),
    description: "For interns interested in project management, operations, and organizational efficiency",
    careerPaths: ["Project Manager", "Operations Manager", "Process Improvement Specialist", "Management Consultant"],
  },
  {
    id: "communications_marketing",
    name: "Communications & Marketing Career Track",
    members: [5],
    sharedInterests: [
      "Content Creation",
      "Digital Marketing",
      "Brand Management",
      "Communication Strategy",
      "Creative Thinking",
    ],
    createdDate: new Date("2025-07-01"),
    description: "For interns interested in communications, marketing, and brand-building careers",
    careerPaths: ["Marketing Manager", "Communications Specialist", "Brand Manager", "Content Strategist"],
  },
]

// Comprehensive skill categories for telecommunications infrastructure
export const skillCategories = [
  "Network Planning",
  "CAD Design",
  "5G Technology",
  "Technical Design",
  "Infrastructure Planning",
  "Business Development",
  "Strategic Planning",
  "Client Relations",
  "Market Research",
  "Commercial Acumen",
  "Cybersecurity",
  "Network Management",
  "Data Analysis",
  "System Design",
  "Cloud Computing",
  "Financial Analysis",
  "Corporate Finance",
  "Investment Evaluation",
  "Risk Assessment",
  "Content Creation",
  "Digital Marketing",
  "Brand Management",
  "Communication Strategy",
  "Creative Thinking",
  "Project Management",
  "Process Optimization",
  "Leadership",
  "Resource Management",
  "Organizational Skills",
  "Quality Management",
  "Performance Metrics",
  "Continuous Improvement",
  "Environmental Science",
  "Sustainability",
  "ESG Frameworks",
  "Renewable Energy",
  "Environmental Impact",
  "Network Engineering",
  "System Performance",
  "Technical Problem Solving",
  "Innovation",
  "Programming",
  "Software Architecture",
  "Database Management",
  "Statistical Analysis",
  "Financial Modeling",
  "Stakeholder Management",
]

// Available interests for selection (same as skill categories for consistency)
export const availableInterests = skillCategories

// Mock Posts Data for Social Feed with Nigerian Telecom Context
export const mockPosts = [
  {
    id: 1,
    author_id: 1,
    author_name: "Adebayo Ogundimu",
    content:
      "Just completed my first 5G tower site survey! The technical complexity of telecommunications infrastructure is fascinating. Learning so much about network planning and regulatory compliance.",
    timestamp: "2025-01-20T10:30:00Z",
    scope: "all",
    squad_id: "siwes_2025_jan",
    mentorship_group_id: "engineering_tech",
    likes: 8,
    comments: 3,
  },
  {
    id: 2,
    author_id: 2,
    author_name: "Chinelo Okechukwu",
    content:
      "Working on a partnership proposal with a major MNO. The commercial dynamics in Nigeria's telecom sector are incredibly complex but exciting! 📡",
    timestamp: "2025-01-22T14:15:00Z",
    scope: "mentorship_group",
    squad_id: "siwes_2025_jan",
    mentorship_group_id: "business_strategy",
    likes: 12,
    comments: 5,
  },
  {
    id: 3,
    author_id: 3,
    author_name: "Ibrahim Musa",
    content:
      "Implemented new cybersecurity protocols for our network monitoring systems. The intersection of IT security and telecommunications infrastructure is my passion!",
    timestamp: "2025-01-23T16:45:00Z",
    scope: "squad",
    squad_id: "siwes_2025_jan",
    mentorship_group_id: "software_tech",
    likes: 15,
    comments: 7,
  },
  {
    id: 4,
    author_id: 4,
    author_name: "Funmilayo Adeyemi",
    content:
      "Analyzing the ROI on our renewable energy initiatives for tower sites. Sustainable infrastructure investment is the future of Nigerian telecommunications!",
    timestamp: "2025-01-24T13:20:00Z",
    scope: "all",
    squad_id: "nysc_2025_batch_a",
    mentorship_group_id: "finance_analytics",
    likes: 10,
    comments: 4,
  },
  {
    id: 5,
    author_id: 5,
    author_name: "Kemi Bamgbose",
    content:
      "Launched our new brand campaign highlighting Nigeria's digital transformation through telecommunications infrastructure. Proud to contribute to this narrative! 🇳🇬",
    timestamp: "2025-01-25T17:30:00Z",
    scope: "all",
    squad_id: "siwes_2025_jul",
    mentorship_group_id: "communications_marketing",
    likes: 18,
    comments: 8,
  },
]

// Mock Ratings Data with Nigerian Names
export const mockRatings = [
  {
    id: 1,
    rater_id: 1,
    rater_name: "Adebayo Ogundimu",
    ratee_id: 2,
    ratee_name: "Chinelo Okechukwu",
    rating: 5,
    feedback:
      "Chinelo brings exceptional commercial insight to our squad discussions. Her understanding of MNO partnerships is impressive!",
    category: "peer",
    timestamp: "2025-01-20T14:30:00Z",
  },
  {
    id: 2,
    rater_id: 2,
    rater_name: "Chinelo Okechukwu",
    ratee_id: 7,
    ratee_name: "Sarah Okonkwo",
    rating: 5,
    feedback:
      "Sarah provides excellent technical guidance and always makes time to explain complex engineering concepts. Outstanding mentor!",
    category: "manager",
    timestamp: "2025-01-21T16:45:00Z",
  },
  {
    id: 3,
    rater_id: 3,
    rater_name: "Ibrahim Musa",
    ratee_id: 1,
    ratee_name: "Adebayo Ogundimu",
    rating: 4,
    feedback:
      "Adebayo's technical curiosity and attention to detail in network planning is remarkable. Great collaboration on infrastructure projects.",
    category: "peer",
    timestamp: "2025-01-22T09:15:00Z",
  },
]

// Mock Announcements Data with Telecom Context
export const mockAnnouncements = [
  {
    id: 1,
    title: "Welcome to Our Infrastructure Team!",
    content:
      "We're excited to welcome our new SIWES, ISAP, TSAP, and NYSC interns to the 2025 cohorts! You're now part of Nigeria's leading telecommunications infrastructure company. Please complete your onboarding in the Network Operations Center by Friday.",
    author: "HR Admin",
    timestamp: "2025-01-15T09:00:00Z",
    type: "announcement",
  },
  {
    id: 2,
    title: "5G Network Expansion Project",
    content:
      "Our Engineering team is launching a major 5G infrastructure project across Lagos, Abuja, and Port Harcourt. Interns in technical departments will have opportunities to contribute to Nigeria's digital transformation. Site visits scheduled for next month.",
    author: "HR Admin",
    timestamp: "2025-01-20T14:30:00Z",
    type: "announcement",
  },
  {
    id: 3,
    title: "NCC Regulatory Compliance Training",
    content:
      "Mandatory training session on Nigerian Communications Commission regulations for all interns. This covers spectrum management, infrastructure sharing, and quality of service standards. Session scheduled for February 5th.",
    author: "HR Admin",
    timestamp: "2025-01-25T10:15:00Z",
    type: "announcement",
  },
]

// Mock Knowledge Base Files with Telecom Context
export const mockKnowledgeFiles = [
  {
    id: 1,
    name: "Employee Handbook 2025.pdf",
    category: "HR Documents",
    size: "2.4 MB",
    type: "pdf",
    uploaded_by: "HR Admin",
    upload_date: "2025-01-10T10:00:00Z",
    downloads: 45,
  },
  {
    id: 2,
    name: "NCC Regulatory Guidelines.docx",
    category: "Regulatory",
    size: "1.8 MB",
    type: "docx",
    uploaded_by: "Regulatory Affairs",
    upload_date: "2025-01-12T14:30:00Z",
    downloads: 38,
  },
  {
    id: 3,
    name: "5G Infrastructure Standards.pdf",
    category: "Technical",
    size: "3.2 MB",
    type: "pdf",
    uploaded_by: "Engineering Team",
    upload_date: "2025-01-15T09:15:00Z",
    downloads: 52,
  },
  {
    id: 4,
    name: "Telecommunications Infrastructure Overview.pptx",
    category: "Onboarding",
    size: "4.1 MB",
    type: "pptx",
    uploaded_by: "HR Admin",
    upload_date: "2025-01-08T11:45:00Z",
    downloads: 67,
  },
  {
    id: 5,
    name: "HSE Safety Protocols for Tower Sites.pdf",
    category: "Safety",
    size: "2.1 MB",
    type: "pdf",
    uploaded_by: "HSE Team",
    upload_date: "2025-01-05T16:20:00Z",
    downloads: 41,
  },
]

// Mock Mentors Data with Nigerian Names and Telecom Expertise
export const mockMentors = [
  {
    id: 101,
    name: "Tunde Adesanya",
    department: "Technical Quality Management & Organisational Performance",
    role: "Senior Quality Manager",
    expertise: ["Quality Management", "Process Optimization", "KPIs", "ISO Standards", "Six Sigma"],
    current_mentees: 2,
    max_mentees: 3,
    rating: 4.8,
    bio: "Quality management expert with 10+ years in telecommunications infrastructure. Specialized in process improvement and performance optimization.",
  },
  {
    id: 102,
    name: "Ngozi Okonkwo",
    department: "Network & Systems Performance",
    role: "Senior Network Engineer",
    expertise: [
      "Network Engineering",
      "System Performance",
      "Telecommunications",
      "Infrastructure Planning",
      "5G Technology",
    ],
    current_mentees: 1,
    max_mentees: 2,
    rating: 4.9,
    bio: "Network engineering specialist with deep expertise in telecommunications infrastructure and emerging 5G technologies.",
  },
  {
    id: 103,
    name: "Segun Oladele",
    department: "Project Delivery",
    role: "Project Delivery Director",
    expertise: ["Project Management", "Infrastructure Development", "Stakeholder Management", "PMP", "PRINCE2"],
    current_mentees: 3,
    max_mentees: 4,
    rating: 4.7,
    bio: "Project management leader with proven track record in delivering complex telecommunications infrastructure projects across Nigeria.",
  },
  {
    id: 104,
    name: "Chioma Eze",
    department: "Sustainability",
    role: "Sustainability Director",
    expertise: [
      "Environmental Science",
      "ESG Frameworks",
      "Renewable Energy",
      "Sustainability Reporting",
      "Environmental Compliance",
    ],
    current_mentees: 1,
    max_mentees: 2,
    rating: 4.6,
    bio: "Sustainability expert driving environmental initiatives in telecommunications infrastructure development across Nigeria.",
  },
]

// Mock Complaints Data with Nigerian Context
export const mockComplaints = [
  {
    id: 1,
    internId: 2,
    internName: "Chinelo Okechukwu",
    type: "poor_treatment",
    description:
      "I've experienced some unprofessional behavior from a team member during client meetings. They frequently interrupt and dismiss my commercial insights without consideration.",
    status: "pending",
    timestamp: "2025-01-18T11:30:00Z",
    hrNotes: "",
  },
  {
    id: 2,
    internId: 3,
    internName: "Ibrahim Musa",
    type: "department_change",
    description:
      "I've discovered a strong interest in network engineering and would like to explore opportunities in the Network & Systems Performance department.",
    requestedDepartment: "Network & Systems Performance",
    reasonForNewDept:
      "I have been working on personal network security projects and feel my technical skills would be better utilized in the Network Performance team. I've also been studying telecommunications protocols and 5G technology.",
    status: "approved",
    timestamp: "2025-01-15T16:20:00Z",
    hrNotes:
      "Approved based on strong technical aptitude and genuine interest in network engineering. Will coordinate with Network & Systems Performance team for transition.",
  },
]

// Mock Departments Data
export const mockDepartments = [
  {
    id: 1,
    name: "Commercial Department",
    description:
      "Drive revenue growth through customer acquisition, partnerships, and lease agreements. Manage client relationships with MNOs, ISPs, and vendors.",
    keyFunctions: [
      "Drive revenue growth (customer acquisition, partnerships, lease agreements)",
      "Manage client relationships (MNOs, ISPs, vendors)",
      "Order to cash processes",
      "Contract negotiations",
    ],
    requiredSkills:
      "Negotiation, communication, relationship management, analytical and strategic thinking, telecoms market knowledge",
    manager: "David Adeleke",
  },
  {
    id: 2,
    name: "Finance Department",
    description:
      "Responsible for financial planning, reporting, budgeting, cash flow management, and ensuring compliance with accounting standards.",
    keyFunctions: [
      "Financial planning, reporting, and budgeting",
      "Cash flow and treasury management",
      "Cost control and investment analysis",
      "Compliance with accounting standards",
    ],
    requiredSkills:
      "Accounting, Finance, Economics background, spreadsheet expertise, data analysis, attention to detail, problem-solving",
    manager: "Kola Adesina",
  },
  {
    id: 3,
    name: "HSE (Health, Safety & Environment)",
    description:
      "Ensure workplace safety standards, conduct risk assessments, manage environmental compliance, and maintain safety culture across operations.",
    keyFunctions: [
      "Ensure workplace safety standards and compliance",
      "Risk assessments and safety training",
      "Environmental sustainability and regulatory compliance",
      "Incident investigation and prevention",
    ],
    requiredSkills:
      "Environmental Science, Engineering, HSE certifications (NEBOSH), risk management, communication, training skills",
    manager: "Adebayo Ogundimu",
  },
  {
    id: 4,
    name: "HR (Human Resources)",
    description:
      "Manage recruitment, employee engagement, performance management, and organizational development to support company growth.",
    keyFunctions: [
      "Recruitment, onboarding, and workforce planning",
      "Employee engagement and learning & development",
      "Performance management and succession planning",
      "Compensation, benefits, and staff welfare",
    ],
    requiredSkills:
      "Interpersonal communication, organizational skills, conflict resolution, coaching, people development focus",
    manager: "Folake Adesanya",
  },
  {
    id: 5,
    name: "Internal Audit",
    description:
      "Evaluate internal controls, review processes for risks, ensure compliance, and detect inefficiencies to improve organizational governance.",
    keyFunctions: [
      "Evaluate and improve internal controls",
      "Review financial and operational processes",
      "Ensure compliance with policies and regulations",
      "Detect fraud and suggest improvements",
    ],
    requiredSkills:
      "Accounting, Finance, Auditing certifications (ACCA, CIA), critical thinking, investigative mindset, ethics",
    manager: "Chinedu Okafor",
  },
  {
    id: 6,
    name: "Legal Department",
    description:
      "Handle contract management, regulatory compliance, corporate governance, and legal risk management across all business operations.",
    keyFunctions: [
      "Drafting and reviewing contracts",
      "Ensuring regulatory and legal compliance",
      "Corporate governance and risk advisory",
      "Managing disputes and external counsel",
    ],
    requiredSkills: "Law degree (LLB/BL), corporate/telecom law, writing, research, negotiation, analytical thinking",
    manager: "Amaka Nwankwo",
  },
  {
    id: 7,
    name: "Technical Quality Management & Organisational Performance",
    description:
      "Develop quality standards, monitor performance metrics, drive continuous improvement, and benchmark organizational performance against industry standards.",
    keyFunctions: [
      "Develop and maintain quality standards",
      "Monitor performance metrics and compliance",
      "Drive continuous improvement initiatives",
      "Support audits and process optimization",
    ],
    requiredSkills:
      "Engineering, Quality Management, process-driven mindset, KPIs, data analysis, improvement frameworks (ISO, Six Sigma)",
    manager: "Tunde Adesanya",
  },
  {
    id: 8,
    name: "Network & Systems Performance",
    description:
      "Ensure high availability of telecom networks and IT systems, monitor KPIs, troubleshoot issues, and optimize network performance.",
    keyFunctions: [
      "Ensure network and system reliability",
      "Monitor network KPIs (uptime, latency, throughput)",
      "Troubleshoot performance issues",
      "Capacity planning and optimization",
    ],
    requiredSkills:
      "Telecommunications, Computer Science, Network Engineering, technical problem-solving, telecom infrastructure knowledge",
    manager: "Ngozi Okonkwo",
  },
  {
    id: 9,
    name: "Project Delivery",
    description:
      "Manage end-to-end execution of technical and infrastructure projects, coordinating stakeholders and ensuring timely, cost-effective completion.",
    keyFunctions: [
      "Manage technical and infrastructure projects",
      "Define scope, timelines, and deliverables",
      "Coordinate stakeholders and vendors",
      "Monitor risks and quality standards",
    ],
    requiredSkills:
      "Project Management, Engineering, organizational leadership, project methodologies (PMP, PRINCE2), infrastructure development",
    manager: "Segun Oladele",
  },
  {
    id: 10,
    name: "Sustainability",
    description:
      "Develop ESG strategy, implement sustainability initiatives, monitor environmental compliance, and drive corporate social responsibility.",
    keyFunctions: [
      "Develop sustainability initiatives (energy efficiency, carbon reduction)",
      "Drive ESG strategy implementation",
      "Monitor environmental compliance",
      "Report sustainability performance",
    ],
    requiredSkills:
      "Environmental Science, Sustainability, ESG frameworks, renewable energy, analytical reporting, environmental impact focus",
    manager: "Chioma Eze",
  },
  {
    id: 11,
    name: "Corporate Communications",
    description:
      "Manage internal and external communications, build corporate brand, handle media relations, and drive employee engagement.",
    keyFunctions: [
      "Manage internal and external communications",
      "Build and protect corporate brand",
      "Handle media relations and public affairs",
      "Support crisis communication",
    ],
    requiredSkills: "Communications, PR, Journalism, Marketing, writing, storytelling, presentation, media management",
    manager: "Kemi Bamgbose",
  },
  {
    id: 12,
    name: "Engineering and Design",
    description:
      "Design tower structures and power systems, oversee installation, integrate green energy solutions, and ensure regulatory compliance.",
    keyFunctions: [
      "Design tower structures and power systems",
      "Oversee installation and testing",
      "Integrate sustainable energy solutions",
      "Plan network layouts for connectivity demands",
    ],
    requiredSkills:
      "Network planning, CAD design, analytical troubleshooting, resource allocation, NCC standards, 5G technology",
    manager: "Sarah Okonkwo",
  },
  {
    id: 13,
    name: "IT Department",
    description:
      "Provide IT solutions, resolve technical issues, manage network infrastructure, and monitor tower performance systems.",
    keyFunctions: [
      "Provide hardware and software solutions",
      "Resolve IT-related issues",
      "Manage network and systems infrastructure",
      "Monitor tower performance systems",
    ],
    requiredSkills:
      "Networks, cybersecurity, server management, troubleshooting, user support, project planning, data analysis",
    manager: "Ibrahim Musa",
  },
]
